<?php

namespace AppBundle\Repository;

/**
 * accesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class accesRepository extends \Doctrine\ORM\EntityRepository
{
}
