<?php

namespace AppBundle\Repository;

/**
 * SeniorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SeniorRepository extends \Doctrine\ORM\EntityRepository
{
}
