<?php

namespace backBundle\Repository;

/**
 * BureauGrilleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BureauGrilleRepository extends \Doctrine\ORM\EntityRepository
{
}
