<?php

namespace backBundle\Repository;

/**
 * Colls_ClientsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Colls_ClientsRepository extends \Doctrine\ORM\EntityRepository
{
}
