<?php

namespace backBundle\Repository;

/**
 * DeptRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeptRepository extends \Doctrine\ORM\EntityRepository
{
}
