<?php

namespace backBundle\Repository;

/**
 * essayeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class essayeRepository extends \Doctrine\ORM\EntityRepository
{
}
